# Homework 4

# Solution Sample

## Part 1: Exam-Style Questions

### Problem 1.1

Suppose that the histogram of orientations $\theta\in [0, 180)$ has 18 equal bins, numbered 0 to 17, and with centers $5, 15, \ldots, 175$. Bilinear voting is used, as described in the class notes on Histograms of Oriented Gradients. Give the fraction of vote that each of the bins receives when a measurement $\theta = 42$ is observed. Fractions are values in $[0, 1]$.

### Answer

The relevant bin centers are 35 and 45 for bins 3 and 4. Bin 3 receives a fraction 0.3 of the vote, bin 4 receives fraction 0.7, and all the other bins receive no part of the vote.

### Problem 1.2

The $x$ and $y$ components of $\nabla I$ at a particular pixel in an image are $10\sqrt{3}$ and $10$, respectively. What are the magnitude and orientation of the gradient there? Express orientation in degrees relative to the $x$ axis.

### Answer

We have $I_x = 20 \cos\theta$ and $Y_y = 20 \sin\theta$ where the orientation $\theta$ is $30$ degrees. The magnitude is $\mu = \sqrt{I_x^2 + I_y^2} = \sqrt{300 + 100} = 20$.

### Problem 1.3

A HOG feature is computed from a $128\times 64$ window divided into cells with $8\times 8$ pixels each. The size of a block is $2\times 2$ cells. Central differences are used to compute gradients. Each cell histogram has nine bins of equal size, and bin 0 is for orientations in $[0, 20)$ degrees.

Rather than using a constant $\epsilon$ in the denominator during normalization of a histogram $\mathbf{v}$, the following procedure is used at all stages to normalize a histogram $\mathbf{v}$ to $\mathbf{v}'$:

$$
\mathbf{v'} \;=\; \left\{\begin{array}{ll} \frac{\mathbf{v}}{\|\mathbf{v}\|} &
\mbox{if $\|\mathbf{v}\| \neq 0$} \\ \mathbf{v} & \mbox{otherwise.}\end{array}\right.
$$

The threshold $\tau$ used to saturate the feature entries during contrast normalization is set to infinity (so that it has no effect).

For a given window, the pixel at position $(5, 5)$ has value 50, and all other pixels are zero.

Give an expression for the entries of the HOG feature $\mathbf{h}$ for that window.

### Answer

The first cell in the window has four pixels where the gradient is nonzero. Two of these gradients contribute evenly to bin 0 and bin 8 (their orientation is 0 degrees, so they contribute evenly to bin 0 and bin 8), and two contribute to bin 4 (their orientation is 90 degrees). The first cell belongs to a single block, the first one, so that the unnormalized histogram for that block, which has 36 entries, has value 50 in entries 0 and 8, and value 100 in entry 4. All other entries equal to zero. After block normalization, this histogram has those entries equal to $\frac{1}{\sqrt{6}}$ and $\frac{2}{\sqrt{6}}$ respectively , and all others equal to zero. The same holds for the concatenation of all the block histograms, as all other blocks have zero histograms.

In conclusion, the $36\times 15\times 7 = 3780$ entries of the final HOG descriptor are as follows, for $0\leq k < 3780$:

$$
h_k \;=\; \left\{\begin{array}{ll} \frac{\sqrt{6}}{6} &
\mbox{if $k = 0$ or $k = 8$} \\
\frac{\sqrt{6}}{3} & \mbox{if $k=4$}\\
 0 & \mbox{otherwise.}\end{array}\right.
$$


### Problem 1.4

The magnitude of a vector $\mathbf{x} = [x, y]^T\in\mathbb{R}^2$ is

$$
            f(x, y) = \sqrt{x^2 + y^2}\;.
$$

Write algebraic expressions and exact decimal numerical values of the gradient $\nabla f$ and Hessian $H_f$ of $f$ at $x=3$ and $y=4$.

[Hint: $1/5^3 = 1/125 = 8/1000$.]

### Answer

$$   
\begin{eqnarray*}
\nabla f(3, 4) &=& \frac{1}{\sqrt{x^2 + y^2}} \left[\begin{array}{c}x\\y\end{array}\right]_{x=3, y=4} = 
\frac{1}{5} \left[\begin{array}{c}3\\4\end{array}\right]
= \left[\begin{array}{c}0.6\\0.8\end{array}\right] \\
H_f(3, 4) &=& \frac{1}{\left(\sqrt{x^2 + y^2}\right)^3}
\left[\begin{array}{cc}y^2 & -xy\\-xy & x^2\end{array}\right]_{x=3, y=4} = 
\frac{1}{125} \left[\begin{array}{rr}16 & -12\\-12 & 9\end{array}\right] \\
&=& \frac{1}{1000} \left[\begin{array}{rr}128 & -96\\-96 & 72\end{array}\right] =
\left[\begin{array}{rr}0.128 & -0.096\\ -0.096 & 0.072\end{array}\right]
\end{eqnarray*}
$$

### Problem 1.5

The second stage of line search repeatedly narrows a bracketing triple $(a, b, c)$ established in the first stage. Suppose that at some point during the second stage the bracketing triple is:

$$
a = 0 \;\;\;,\;\;\; b = 2 \;\;\;,\;\;\; c = 6
$$

with function values

$$
h(a) = 6 \;\;\;,\;\;\; h(b) = 3 \;\;\;,\;\;\; h(c) = 4
$$

along the search line. Assume further that

$$
h(1) = 2 \;\;\;\text{and}\;\;\; h(4) = 5\;.
$$

What is the bracketing triple after that? Standard line search is applied, that is, no golden ratio is used. No need to explain.

[Hint: Draw a sketch.]

### Answer

The wider interval is $(b, c)$, so the new point is $u=(b+c)/2 = 4$. Since $6 = h(a) > h(b) = 3\;$ and $\;3 = h(b) < h(u) = 5$, the new bracketing triple is

$$
    (a, b, u) = (0, 2, 4)\;.
$$

### Problem 1.6

The gradient and Hessian at $\mathbf{z}_0 = [4, 1]^T$ for some function $f\ :\ \mathbb{R}^2 \rightarrow \mathbb{R}$ are as follows:

$$
\nabla f(\mathbf{z}_0) \;=\; \left[\begin{array}{c}2\\1 \end{array}\right]
\;\;\;\text{and}\;\;\;
H_f(\mathbf{z}_0) \;=\; \left[\begin{array}{c}2 & 1\\1 & 3 \end{array}\right] \;.
$$

Find the point $\mathbf{z}_1$ that results by taking a single Newton step from $\mathbf{z}_0$. Show your reasoning briefly.

### Answer

Newton's method determines the change $\Delta\mathbf{z} = \mathbf{z}_1 - \mathbf{z}_0$ by solving the system

$$
H_f(\mathbf{z}_0)\, \Delta\mathbf{z} \;=\; - \nabla f(\mathbf{z}_0)
$$

that is,

$$
\left[\begin{array}{c}2 & 1\\1 & 3 \end{array}\right] \, \Delta\mathbf{z} \;=\; - \left[\begin{array}{c}2\\1 \end{array}\right]\;.
$$

Other than for a sign flip, the right-hand side of this equation is the first column of the Hessian, so that

$$
\Delta\mathbf{z} \;=\; \mathbf{z}_1 - \mathbf{z}_0 \;=\; \left[\begin{array}{r} -1\\0 \end{array}\right]
$$

and therefore

$$
\mathbf{z}_1 \;=\; \mathbf{z}_0 + \Delta\mathbf{z} \;=\; \left[\begin{array}{r} 4\\1 \end{array}\right] -
\left[\begin{array}{r} 1\\0 \end{array}\right] \;=\; \left[\begin{array}{r} 3\\1 \end{array}\right] \;.
$$

### Problem 1.7

A classification problem asks to find a classifier $h\in\mathcal{H}$ whose domain $X$ and co-domain $Y$ of $h$ are defined as follows:

$$
X = \{0, 2, 4, 6, 8, 10\} \;\;\;\text{and}\;\;\; Y = \{0, 1\}
$$

and the hypothesis space $\mathcal{H}$ is the set of the following five functions

$$
h_k(x) = \left\{\begin{array}{ll}0 & \mbox{if $x < k$}\\
1 & \mbox{otherwise}\end{array}\right.
\;\;\;\text{for}\;\;\; k = 1, 3, 5, 7, 9\;.
$$

The following tiny training set is given:

$$
T = \{(0, 0), (2, 0), (4, 1), (6, 1) \} \;.
$$

Make a table of the training risk $L_T(h_k)$ for $k = 1, 3, 5, 7, 9$.  Express values in percent. Then use the table to determine the optimal classifier $\hat{h}$ for this training set (thus, we only care about empirical risk here).

### Answer

$$
\begin{array}{r|ccccc}
k & 1 & 3 & 5 & 7 & 9 \\\hline
L_T(h_k) & 25 & 0 & 25 & 50 & 50 
\end{array}
$$

The optimal classifier on $T$ is $\hat{k} = h_3$.

### Problem 1.8

Assume that the probability model $p(x, y)$ for the data in Problem 1.7 is as specified in the table below. The table contains the joint probability $p(x, y)$ with values expressed in percent, rather than as numbers in $[0, 1]$. It has one column per value of $x$ and one row per value of $y$.

$$
\begin{array}{c|ccccccc}
 & 0 & 2 & 4 & 6 & 8 & 10 \\\hline
0 & 12 & 11 & 10 & 7 & 6 & 4 \\
1 & 2 & 4 & 6 & 10 & 12 & 16
\end{array}
$$

Under the same circumstances as in Problem 1.7, and with the probability model above, make a table of the statistical risk $L_p(h)$ and determine the classifier that generalizes best. Express values in percent.

### Answer

$$
\begin{array}{r|ccccc}
k & 1 & 3 & 5 & 7 & 9 \\\hline
L_p(h_k) & 40 & 33 & 29 & 32 & 38 
\end{array}
$$

The classifier that generalizes best is $\hat{k} = h_5$.

## Part 2: Projections

### Problem 2.1

What is the shape (number of rows and columns) of $U$? Explain briefly.

### Answer

The matrix $U$ is $m\times (m-1)$, because the dimensions of a space and its orthogonal complement add up to the dimension $m$ of the ambient space. The space spanned by $\mathbf{u}$ has dimension 1, and $\mathcal{O}(\mathbf{u})$ is its orthogonal complement, which therefore has dimension $m-1$. It takes $m-1$ vectors to span a space of dimension $m-1$.

### Problem 2.2

Explain clearly how, given $\mathbf{u}$, you can use the Singular Value Decomposition (SVD) to compute a matrix whose columns form an orthonormal basis for $\mathcal{O}(\mathbf{u})$. Also explain why.

Then show a basis for $\mathcal{O}([1, 1, 0]^T)$ using your technique.

Give the projection matrix $P$ for this space, and the projection of the vector $\mathbf{b} = [0, 2, -4]^T$ onto $\mathcal{O}([1, 1, 0]^T)$.

Use whatever code you'd like, but do **not** submit your code. Give your numerical results either exactly (if you can guess what they are) or with four decimal digits after the period.

Do **not** use any other techniques, such as Gram-Schmidt.

### Answer

If $A = U_A \Sigma V^T$ is the SVD of $A$, then the desired matrix is all of $U_A$ except the first column.

This is because the first column of $U_A$ spans the range of $\mathbf{u}$, viewed as a matrix. The left null space of that matrix is then $\mathcal{O}(\mathbf{u})$, and that is spanned by the columns of $U_A$ after the first, because $\mathbf{u}$ viewed as a matrix has rank 1.

Applying this technique with $\mathbf{u} = [1, 1, 0]^T$ yields

$$
U = \left[\begin{array}{rr}-\frac{\sqrt{2}}{2} & 0\\
\frac{\sqrt{2}}{2} & 0\\
0 & 1\end{array}\right] \;.
$$

With these values, we obtain

$$
P = UU^T = \frac{1}{2} \left[\begin{array}{rrr}
1 & -1 & 0\\
-1 & 1 & 0\\
0 & 0 & 2
\end{array}\right] \;.
$$

The projection of $\mathbf{b} = [0, 2, -4]^T$ onto $\mathcal{O}([1, 1, 0]^T)$ is

$$
\mathbf{p} = P \mathbf{b} = \left[\begin{array}{r}-1\\1\\-4 \end{array}\right] \;.
$$

### Problem 2.3

For each of the two matrices $U$ and $P$ and the vector $\mathbf{p}$ you found in the previous problem, state whether the object is unique, and explain briefly why or why not.

### Answer

The matrix $U$ is not unique, because the last two singular values of $\mathbf{u}$ viewed as a matrix are equal to each other (and to zero). More intuitively, given any orthonormal basis for $\mathcal{O}(\mathbf{u})$, one can obtain an infinity of other orthonormal bases by rotating and/or flipping the directions of the original basis vectors.

$P$ and $\mathbf{p}$, on the other hand, are unique. This is because they express either the projection map or its image, and the projection of a vector $\mathbf{b}$ onto a subspace is unique, being the vector in the subspace that is closest to $\mathbf{b}$.

### Problem 2.4

Compute the matrix $$Q = I - \mathbf{n}\mathbf{n}^T$$ for the example given in Problem 2.2.

Show $Q$ if it is different from the matrix $P$ you obtained through SVD. Otherwise, just state that the two matrices are the same.

### Answer

The two matrices are the same.

## Part 3: Optimization and the SVD

In [1]:
import numpy as np
from scipy.optimize import minimize_scalar

def normalize(v):
    n = np.linalg.norm(v)
    if n > 0:
        v = v / n
    return v, n

# sphere_search returns a new point z1, not a search step size
def sphere_step(f, g, z0, epsilon=1.e-6, args=()):
    assert epsilon > 0 and epsilon < 1, 'epsilon must be in (0, 1)'
    assert z0.size > 1, 'sphere must be at least 2-dimensional'
    
    n0, delta = 0, 0
    while n0 < epsilon:
        z0 += delta * np.sqrt(epsilon) * np.random.random(z0.shape)
        z0, _ = normalize(z0)
        p0 = -g(z0, *args)  # Starting direction
        # Project p0 onto the tangent hyperplane to the sphere at z0 and normalize
        s0, n0 = normalize(p0 - np.dot(z0, p0) * z0)
        delta = 1
    
    def h(theta, args):
        return f(z0 * np.cos(theta) + s0 * np.sin(theta), args)
    
    res = minimize_scalar(h, bracket=(0, 1), args=args)
    theta = res.x
    return z0 * np.cos(theta) + s0 * np.sin(theta)

### Problem 3.1

Write a function with the following header and `assert` statements:

    def first(A, epsilon=1.e-6, maxiter=10):
        assert A.size > 0, 'array cannot be empty'
        assert np.max(np.abs(A)) >= epsilon, 'array cannot be zero'

that uses `sphere_step` iteratively to return the tuple `u, sigma, v` of the first left singular vector, first singular value, and first right singular vector of `A`.

Show your code and the results of running the given tests. You may want to compare your results with those obtained with an off-the-shelf implementation of the SVD. However, do **not** submit your comparison, and do not use SVDs anywhere in your code.

### Answer

In [2]:
def first(A, epsilon=1.e-3, maxiter=10):
    assert A.size > 0, 'array cannot be empty'
    assert np.max(np.abs(A)) >= epsilon, 'array cannot be zero'
    
    def f(u, A):
        v = np.dot(A, u)
        return -np.dot(v, v)
    
    def g(u, A):
        return -2 * np.dot(A.T, np.dot(A, u))

    if np.min(A.shape) < 2:
        x, sigma = normalize(A)
        x, one = np.squeeze(x), np.array(1)
        if A.shape[0] == 1:
            u, v = (one, x)
        else:
            u, v = (x, one)
    else:    
        old_v = A[0]
        for k in range(maxiter):
            v = sphere_step(f, g, old_v, epsilon=epsilon, args = (A,))
            if np.linalg.norm(v - old_v) < epsilon:
                break
            old_v = v
        u = np.dot(A, v)
        sigma = np.linalg.norm(u)
        if sigma > epsilon:
            u = u / sigma
        
    return u, sigma, v


In [3]:
def test(f, A_list):
    def printArray(name, A):
        print(name, A, sep='\n', end='\n\n')
        
    if f.__name__ is 'first':
        un, sn, vn = 'u', 'sigma', 'v'
        product = False
    else:
        un, sn, vn = 'U', 'Sigma', 'V'
        product = True

    np.set_printoptions(precision=4, suppress=True)
    
    for A in A_list:
        U, Sigma, V = f(A)
        print('=' * 10, 'testing', f.__name__, '=' * 10)
        printArray('A', A)
        if product:
            printArray("U * Sigma * V'", np.dot(U, np.dot(Sigma, V.T)))
        printArray(un, U)
        printArray(sn, Sigma)
        printArray(vn, V)
            
s3 = np.sqrt(3)
A_list = (np.array([[s3, s3], [-3., 3.], [1., 1.]]) / np.sqrt(2.),
          np.outer([1., 2., 3.], [2., 0., -1., 3.]),
          np.array([[3.], [0.], [4.]]), np.array([[4., -3.]]))

try:
    test(first, A_list)
except NameError:
    pass


========== testing first ==========
A
[[ 1.2247  1.2247]
 [-2.1213  2.1213]
 [ 0.7071  0.7071]]

u
[ 0. -1.  0.]

sigma
2.999999999999999

v
[ 0.7071 -0.7071]

========== testing first ==========
A
[[ 2.  0. -1.  3.]
 [ 4.  0. -2.  6.]
 [ 6.  0. -3.  9.]]

u
[0.2673 0.5345 0.8018]

sigma
14.000000000000002

v
[ 0.5345  0.     -0.2673  0.8018]

========== testing first ==========
A
[[3.]
 [0.]
 [4.]]

u
[0.6 0.  0.8]

sigma
5.0

v
1

========== testing first ==========
A
[[ 4. -3.]]

u
1

sigma
5.0

v
[ 0.8 -0.6]



### Problem 3.2

Use your function `first` to write a function with the following header and `assert` statement that computes the "tiny" SVD of a non-empty matrix $A$, with the given specifications:

    def SVD(A, epsilon=1.e-3, maxiter=10):
        assert A.size > 0, 'array cannot be empty'
        
The function should return the tuple `U, Sigma, V` of the matrices in the "tiny" SVD of `A`, and should comply with the programming notes.
        
Show your code and the results of running the given tests. You may want to compare your results with those obtained with an off-the-shelf implementation of the SVD. However, do **not** submit your comparison. Do not use library SVDs anywhere in your code.

### Answer

In [4]:
def SVD(A, epsilon=1.e-3, maxiter=10):
    assert A.size > 0, 'array cannot be empty'

    m, n = A.shape
    p = np.min(A.shape)
    U, Sigma, V = np.zeros((m, p)), np.zeros((p, p)), np.zeros((n, p))
    r = 0
    for j in range(p):
        if np.max(np.abs(A)) < epsilon:
            break
        r += 1
        u, sigma, v = first(A)
        U[:, j], Sigma[j, j], V[:, j] = u, sigma, v
        A = A - np.outer(np.dot(A, v), v)
    if r < p:
        U, Sigma, V = U[:, :r], Sigma[:r, :r], V[:, :r]
    return U, Sigma, V

In [5]:
s3 = np.sqrt(3)
A_list = (np.array([[s3, s3], [-3., 3.], [1., 1.]]) / np.sqrt(2.),
          np.outer([1., 2., 3.], [2., 0., -1., 3.]),
          np.array([[3.], [0.], [4.]]), np.array([[4., -3.]]))

try:
    test(SVD, A_list)
except NameError:
    pass

========== testing SVD ==========
A
[[ 1.2247  1.2247]
 [-2.1213  2.1213]
 [ 0.7071  0.7071]]

U * Sigma * V'
[[ 1.2247  1.2247]
 [-2.1213  2.1213]
 [ 0.7071  0.7071]]

U
[[-0.     0.866]
 [-1.    -0.   ]
 [-0.     0.5  ]]

Sigma
[[3. 0.]
 [0. 2.]]

V
[[ 0.7071  0.7071]
 [-0.7071  0.7071]]

========== testing SVD ==========
A
[[ 2.  0. -1.  3.]
 [ 4.  0. -2.  6.]
 [ 6.  0. -3.  9.]]

U * Sigma * V'
[[ 2.  0. -1.  3.]
 [ 4.  0. -2.  6.]
 [ 6.  0. -3.  9.]]

U
[[0.2673]
 [0.5345]
 [0.8018]]

Sigma
[[14.]]

V
[[ 0.5345]
 [ 0.    ]
 [-0.2673]
 [ 0.8018]]

========== testing SVD ==========
A
[[3.]
 [0.]
 [4.]]

U * Sigma * V'
[[3.]
 [0.]
 [4.]]

U
[[0.6]
 [0. ]
 [0.8]]

Sigma
[[5.]]

V
[[1.]]

========== testing SVD ==========
A
[[ 4. -3.]]

U * Sigma * V'
[[ 4. -3.]]

U
[[1.]]

Sigma
[[5.]]

V
[[ 0.8]
 [-0.6]]

